name: Deploy to Firebase Functions
'on':
  push:
    branches:
      - main
      - firebase-token-auth
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g firebase-tools 
      - run: export FIREBASE_TOKEN=${{ FIREBASE_TOKEN }}
      - run: firebase deploy --only functions --debug
